# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(1A1919)
$foreground = rgb(F6F0E7)
$color0 = rgb(414040)
$color1 = rgb(161212)
$color2 = rgb(54311A)
$color3 = rgb(193975)
$color4 = rgb(5E6B8D)
$color5 = rgb(A97431)
$color6 = rgb(AC9E8C)
$color7 = rgb(EAE1D5)
$color8 = rgb(A39D95)
$color9 = rgb(1E1818)
$color10 = rgb(704123)
$color11 = rgb(214C9C)
$color12 = rgb(7D8FBC)
$color13 = rgb(E19A41)
$color14 = rgb(E5D3BB)
$color15 = rgb(EAE1D5)
