# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(332B29)
$foreground = rgb(DCCCB8)
$color0 = rgb(59504D)
$color1 = rgb(321D15)
$color2 = rgb(25261A)
$color3 = rgb(24271A)
$color4 = rgb(162931)
$color5 = rgb(292B19)
$color6 = rgb(735326)
$color7 = rgb(C4AE91)
$color8 = rgb(897A65)
$color9 = rgb(42271C)
$color10 = rgb(323322)
$color11 = rgb(303423)
$color12 = rgb(1D3742)
$color13 = rgb(373A21)
$color14 = rgb(9A6E33)
$color15 = rgb(C4AE91)
