# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(181818)
$foreground = rgb(DCDDDD)
$color0 = rgb(3F3F3F)
$color1 = rgb(17181A)
$color2 = rgb(1D1E1F)
$color3 = rgb(434445)
$color4 = rgb(4A4B4C)
$color5 = rgb(69696B)
$color6 = rgb(757677)
$color7 = rgb(C5C6C7)
$color8 = rgb(8A8A8B)
$color9 = rgb(1F2022)
$color10 = rgb(27282A)
$color11 = rgb(595A5C)
$color12 = rgb(636466)
$color13 = rgb(8B8C8E)
$color14 = rgb(9C9D9F)
$color15 = rgb(C5C6C7)
