# ============================================================
# KITTY CONFIGURATION
# ============================================================

# ------------------------------------------------------------
# Theme
# ------------------------------------------------------------

include ./kitty-themes/00-Default.conf


# ------------------------------------------------------------
# Font
# ------------------------------------------------------------

font_family FantasqueSansM Nerd Font Mono Bold
font_size 16.0

bold_font auto
italic_font auto
bold_italic_font auto


# ------------------------------------------------------------
# Window
# ------------------------------------------------------------

background_opacity 0.90
dynamic_background_opacity yes

confirm_os_window_close 0

window_padding_width 8

linux_display_server auto


# ------------------------------------------------------------
# Cursor
# ------------------------------------------------------------

cursor_trail 1
cursor_trail_decay 0.1 0.4

cursor_shape block
cursor_blink_interval 0.6


# ------------------------------------------------------------
# Scrolling
# ------------------------------------------------------------

scrollback_lines 10000

wheel_scroll_min_lines 1


# ------------------------------------------------------------
# Bell
# ------------------------------------------------------------

enable_audio_bell no


# ------------------------------------------------------------
# Selection
# ------------------------------------------------------------
# selection_foreground none
# selection_background none


# ------------------------------------------------------------
# Performance
# ------------------------------------------------------------

repaint_delay 10
input_delay 3


# ============================================================
# COLORS
# Managed by Wallust
# ============================================================

allow_remote_control socket-only
listen_on unix:/tmp/kitty


# Do NOT define foreground/background/cursor here.
# Wallust controls them through:
#
# kitty-themes/01-Wallust.conf
#
# ============================================================


# BEGIN_KITTY_THEME
# Solarized8 Dark
include current-theme.conf
# END_KITTY_THEME