[General]
autodetectLanguage=true
backgroundCheckerEnabled=true
checkUppercase=true
checkerEnabledByDefault=false
defaultClient=
defaultLanguage=en_US
preferredLanguages=en_US, en_GB, en_IN
skipRunTogether=true
