[SettingsWindow]
geometry=@ByteArray(\x1\xd9\xd0\xcb\0\x3\0\0\0\0\0\0\0\0\0\0\0\0\x4\xef\0\0\x5_\0\0\0\0\0\0\0\0\0\0\t\xff\0\0\x5s\0\0\0\0\x2\0\0\0\n\0\0\0\0\0\0\0\0\0\0\0\x4\xef\0\0\x5_)

[Interface]
wheel_scroll_lines=3
stylesheets=@Invalid()
gui_effects=General, AnimateMenu, AnimateCombo, AnimateTooltip, AnimateToolBox
double_click_interval=400
cursor_flash_time=1000
show_shortcuts_in_context_menus=true
underline_shortcut=1
keyboard_scheme=2
dialog_buttons_have_icons=1
toolbutton_style=4
activate_item_on_single_click=1
buttonbox_layout=0
menus_have_icons=true

[Appearance]
custom_palette=true
style=kvantum
icon_theme=breeze-dark
standard_dialogs=xdgdesktopportal
cosmic_qt_version=2
color_scheme_path=/home/patrik/.config/qt6ct/colors/CosmicDark.conf

[Troubleshooting]
ignored_applications=@Invalid()
force_raster_widgets=1

[Fonts]
general="Fira Code Medium,14,-1,5,500,0,0,0,0,0,0,0,0,0,0,1,Regular"
fixed="Fira Code Medium,12,-1,5,500,0,0,0,0,0,0,0,0,0,0,1,Regular"
