[SettingsWindow]
geometry=@ByteArray(\x1\xd9\xd0\xcb\0\x3\0\0\0\0\0\0\0\0\0\0\0\0\x4\xef\0\0\x5_\0\0\0\0\0\0\0\0\0\0\t\xff\0\0\x5s\0\0\0\0\x2\0\0\0\n\0\0\0\0\0\0\0\0\0\0\0\x4\xef\0\0\x5_)

[Appearance]
style=kvantum
custom_palette=true
standard_dialogs=xdgdesktopportal

[Interface]
wheel_scroll_lines=3
dialog_buttons_have_icons=1
show_shortcuts_in_context_menus=true
gui_effects=General, AnimateMenu, AnimateCombo, AnimateTooltip, AnimateToolBox
buttonbox_layout=0
activate_item_on_single_click=1
menus_have_icons=true
keyboard_scheme=2
cursor_flash_time=1000
underline_shortcut=1
stylesheets=@Invalid()
double_click_interval=400
toolbutton_style=4

[Troubleshooting]
force_raster_widgets=1
ignored_applications=@Invalid()

[Fonts]
general="Fira Code Medium,14,-1,5,500,0,0,0,0,0,0,0,0,0,0,1,Regular"
fixed="Fira Code Medium,12,-1,5,500,0,0,0,0,0,0,0,0,0,0,1,Regular"
