# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# /* wallust template - colors-kitty */

foreground         #F6F0E7
background         #1A1919
cursor             #B39885

active_tab_foreground     #1A1919
active_tab_background     #F6F0E7
inactive_tab_foreground   #F6F0E7
inactive_tab_background   #1A1919

active_border_color   #F6F0E7
inactive_border_color #1A1919
bell_border_color     #161212

color0      #414040
color1		#161212
color2		#54311A
color3		#193975
color4		#5E6B8D
color5		#A97431
color6		#AC9E8C
color7		#EAE1D5
color8		#A39D95
color9		#1E1818
color10		#704123
color11		#214C9C
color12		#7D8FBC
color13		#E19A41
color14		#E5D3BB
color15		#EAE1D5
