# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# /* wallust template - colors-kitty */

foreground         #DCDDDD
background         #181818
cursor             #828284

active_tab_foreground     #181818
active_tab_background     #DCDDDD
inactive_tab_foreground   #DCDDDD
inactive_tab_background   #181818

active_border_color   #DCDDDD
inactive_border_color #181818
bell_border_color     #17181A

color0      #3F3F3F
color1		#17181A
color2		#1D1E1F
color3		#434445
color4		#4A4B4C
color5		#69696B
color6		#757677
color7		#C5C6C7
color8		#8A8A8B
color9		#1F2022
color10		#27282A
color11		#595A5C
color12		#636466
color13		#8B8C8E
color14		#9C9D9F
color15		#C5C6C7
