# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# /* wallust template - colors-kitty */

foreground         #F6DED1
background         #111215
cursor             #949D9A

active_tab_foreground     #111215
active_tab_background     #F6DED1
inactive_tab_foreground   #F6DED1
inactive_tab_background   #111215

active_border_color   #F6DED1
inactive_border_color #111215
bell_border_color     #073645

color0      #393A3C
color1		#073645
color2		#26454A
color3		#3D6D71
color4		#447B7E
color5		#787366
color6		#AC7A5D
color7		#EAC8B5
color8		#A38C7F
color9		#09485C
color10		#325B62
color11		#519296
color12		#5BA4A7
color13		#A09988
color14		#E5A27C
color15		#EAC8B5
