# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# This is where you put your own keybinds. Be Mindful to check as well ~/.config/hypr/configs/Keybinds.conf to avoid conflict
# if you think I should replace the Pre-defined Keybinds in ~/.config/hypr/configs/Keybinds.conf , submit an issue or let me know in DC and present me a valid reason as to why, such as conflicting with global shortcuts, etc etc

# See https://wiki.hyprland.org/Configuring/Keywords/ for more settings and variables
# See also Laptops.conf for laptops keybinds 

# /* ---- ✴️ Variables ✴️ ---- */  #
$mainMod = SUPER
$scriptsDir = $HOME/.config/hypr/scripts
$UserScripts = $HOME/.config/hypr/UserScripts
$UserConfigs = $HOME/.config/hypr/UserConfigs

#  IMPORTANT: If you want to remap and existing keybind you MUST unbindd it first 

# The bindings are CASE SENSITIVE. We suggest you copy the exisitng binding here
#  Then change `bindd` to `unbind`


# -------------------------------------------------
# --Dedicated Media & Tool Keys (EvoFox Keyboard)--
# -------------------------------------------------

bindd = , XF86Tools, online music, exec, $UserScripts/RofiBeats.sh
bindd = , XF86Calculator, calculator, exec, $UserScripts/RofiCalc.sh
bindd = , XF86HomePage, open notification panel, exec, swaync-client -t -sw
bindd = , XF86Mail, open mail, exec, thunderbird


# -------------------------------------
# -- HP EliteBook Function Key Fixes --
# -------------------------------------

# F1: Display Switch (Opens nwg-displays or monitors selector)
bindl = , XF86Display, exec, nwg-displays

# F8: Mic Mute (Toggles default audio source / mic mute across all endpoints)
bind = , code:248, exec, /home/patrik/.config/hypr/scripts/toggle-mic.sh

# F5: Universal Audio Mute (Toggles default audio sink / output mute)
bindl = , XF86AudioMute, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle

# F12: HP Programmable Key (Launch your terminal or app of choice)
bind = , XF86Launch8, exec, bash /home/patrik/.config/hypr/scripts/vpn.sh

# PrtSc: Screenshot (JaKooLit screenshot script or grimblast)
bind = , Print, exec, $HOME/.config/hypr/UserScripts/QuickEdit.sh || grimblast --notify copysave screen

bind = $mainMod ALT, slash, exec, $HOME/.config/hypr/UserScripts/toggle-rotate.sh

# E.g. 
# unbind = $mainMod, Return, Open terminal, exec, $term
# bindd = $mainMod, Return, Open terminal, exec, ghostty 
#
# unbind = $mainMod, E, file manager, exec, $files
# bindd = $mainMod, T, file manager, exec, $files

# If you are ADDING a bindd, make sure you include the description 
# Other the keybind search menu might not show it properly 

# E.g.
# bindd = $mainMod, Z, My z app, exec APPNAME









# For passthrough keyboard into a VM
# bind = $mainMod ALT, P, submap, passthru
#submap = passthru
# to unbind
#bind = $mainMod ALT, P, submap, reset
#submap = reset

# Launch Media/Stats Dashboard
bind = $mainMod, Home, exec, /home/patrik/.config/hypr/UserScripts/Dashboard.sh
