# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# For window rules and layerrules
# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more

# This file is used to add or overwrite window rules 
# This file will not be modified during dotfiles updates
#
# Disable hyprbars on Firefox & native CSD apps




# Disable hyprbars on Firefox & native CSD apps
#windowrule = plugin:hyprbars:nobar = 1, match:class ^(org\.mozilla\.firefox|firefox)$
#windowrule = plugin:hyprbars:nobar = 1, match:class ^(Google-chrome|google-chrome)$
#windowrule = plugin:hyprbars:nobar = 1, match:class ^(zen-browser|zen)$
#windowrule = plugin:hyprbars:nobar = 1, match:class ^(thunderbird|org\.mozilla\.Thunderbird)$
#windowrule = plugin:hyprbars:nobar = 1, match:class ^(steam)$


