# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# For window rules and layerrules
# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more

# This file is used to add or overwrite window rules 
# This file will not be modified during dotfiles updates
#
# Disable hyprbars on Firefox & native CSD apps

# Disable hyprbars for apps with native titlebars/headerbars
windowrule = hyprbars:no_bar on, match:class ^(org\.mozilla\.firefox|firefox)$
windowrule = hyprbars:no_bar on, match:class ^(zen-browser)$
#windowrule = hyprbars:no_bar on, match:class ^(spotify)$
windowrule = hyprbars:no_bar on, match:class ^(VirtualBox.*|VirtualBox Machine)$

# SwayNC Blur and Transparency
#layerrule = match:namespace swaync-control-center, blur on
#layerrule = match:namespace swaync-control-center, ignore_alpha 0.5
#layerrule = match:namespace swaync-notification-window, blur on
#layerrule = match:namespace swaync-notification-window, ignore_alpha 0.5





# Float common Java / JetBrains / Swing dialogs
windowrule = match:class ^(.*jetbrains.*)$, match:title ^(win.*)$, float on
windowrule = match:class ^(.*java.*)$, match:title ^(.*Dialog.*)$, float on
windowrule = match:class ^(.*java.*)$, match:title ^(.*Choice.*)$, float on



# SwayNC Blur and Transparency
layerrule = match:namespace swaync-control-center, blur on
layerrule = match:namespace swaync-control-center, ignore_alpha 0.5
layerrule = match:namespace swaync-notification-window, blur on
layerrule = match:namespace swaync-notification-window, ignore_alpha 0.5
