# HP EliteBook laptop configuration

$mainMod = SUPER
$scriptsDir = $HOME/.config/hypr/scripts

# Actual touchpad detected by Hyprland:
# syna30b8:00-06cb:ce1a-touchpad

$Touchpad_Device = syna30b8:00-06cb:ce1a-touchpad

# Keyboard brightness
binde = , xf86KbdBrightnessDown, exec, $scriptsDir/BrightnessKbd.sh --dec
binde = , xf86KbdBrightnessUp, exec, $scriptsDir/BrightnessKbd.sh --inc

# Display brightness
binde = , xf86MonBrightnessDown, exec, $scriptsDir/Brightness.sh --dec
binde = , xf86MonBrightnessUp, exec, $scriptsDir/Brightness.sh --inc

# Touchpad toggle
bind = , xf86TouchpadToggle, exec, $scriptsDir/TouchPad.sh

# Screenshots
bind = $mainMod, F6, exec, $scriptsDir/ScreenShot.sh --now
bind = $mainMod SHIFT, F6, exec, $scriptsDir/ScreenShot.sh --area
bind = $mainMod CTRL, F6, exec, $scriptsDir/ScreenShot.sh --in5
bind = $mainMod ALT, F6, exec, $scriptsDir/ScreenShot.sh --in10
bind = ALT, F6, exec, $scriptsDir/ScreenShot.sh --active

# Touchpad
$TOUCHPAD_ENABLED = true

device {
    name = $Touchpad_Device
    enabled = $TOUCHPAD_ENABLED
}
